spring.application.name=netflix-auth-service
spring.datasource.url=jdbc:mysql://localhost:3306/netflix_auth_db
spring.datasource.username=root
spring.datasource.password=bharatmarwah2804

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


jwt.private.key=MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDJG5muG24dqscsYLCzwGoV9jb1o0Xo0hZ6YiIHm1fv3oD5qVdYDk8UZUNlYR5UJkpE64oVc1p+3xFvmlK+KHBGMhxmmjT3s9QzwPhAPd/pyS3Q8kI9vsd4MLuBC1/8a/Vqk2fdUwQYdCIJfnthH7FztKF5SAMXc6QBTT5LeLAyEucXjVs0p1jSJomt5Dtwuk9nubgJsTf2xCUkQi/TY/BbiatdI/1iiepxoemsanOC8fvJI/BWWM0gBWmfoRJSn1SfWIL5ZwO0W0OFXr2OiBgENE4ZGLngsySBAqYBKG/T/8EgZTiFhXTHiQoRWnB8S5L6Er/fMPOM6mR7eMR6Ny8lAgMBAAECggEAKpTl/tf/AlgZMRvN/ll0/O5zp6IpGMl3CfXCV9L8FSWLMJG7FUF+XAau9QXRyqaK3jnzNGSG2ks4IWXPNEVStIJCwjTPl00j1st6pPuU8CbxRQcuoG1HRfsnkITMj6F6RtUsTlAYE2dvl4wI6sEvrRynfgsR4ILTTJVC5e8Je6hl1MTkdsjY2VDqLtovZWUywbNatR8JvOM0W3ZqYZb35aJIb56dkSEuKwZsqbYUdhodsvvu0ZLZAx3qrSj7ak3DF86ChpNdpctIh0OBrgkIlb3BuqecQpqv6c5sPruxEt96eWzy42/QLHFPJDuHAQNc8+nh2p42yXusjxqiAyVBsQKBgQDb8TNKfkNXF+fvxyPwxfNvJxRqy1isHWfxrhoSdL65GT3QcQ7uA9MmBEok1l7Ywp3s/1dkFvN8ihNWr8icY/oDKHFsnmEioIAo1LLrMAgEzBRnN0Ifuh8ymBOpsGmcsJduLd4kouEoWOJ03Z3CWIo9maFm0I+7Hq0OhQWK1wcJnQKBgQDqE++meUibu3KzGzPZJJ4xwBz/PBTX0ji/b6YJnH8hF10J4nEmuv0RoU95DB9cD2DpKSp2neBfpkh0FcXMdZyFLJmBZFUL8Ime5m3o5zVpdfBoKU+BdBcOzOBfnIFSOCSCo25qX7Dg3SEuNB8PvY/8CPQ5u05aCkJHebwoslapKQKBgQCTXYYXSIhIJ51g3BYpsghMlmuornzIPZ+yoAuaCBzuGop/SfFN6sQj+cXP7s53/9YewGtGhdY4wK76aydIGfie+w8cTvYYZF/ae8Exsen9hNu62Jx2c5eJp7ms/aWVtgCQcy0fcP7ZsMxyrzaPzBE7+t7Y668SGhir3Nb80txFRQKBgQCWjrYhJHdwO3P+AawqqaPaqg+8lz9sxblcYIqyOeeHOEjOd8iBudnWgiPk3sg45WdW8PRwEQHlY8XMbMipxqgi/FnL4OXW5SMPgnUFTdmL+KDlzlRmFm5SRbK3rKl9YcESCd6WKvBQ4cpatomYDTxURsoXbANsZJbW9FTy9CpLaQKBgQDFPghClbhkxskHsXLJbb9bM5qweyRXJgdKONXbjgbBzDITZY8Mp/rw4D95RFe80BspFm5W1jbhOtkzjeiLv83p+Nkcrhfm0+hZviQP5Zfvz77o93zD38iVZT3O78HDfl6+64NBiEQHeSxVqIPz9qKKQi+feRyq1uC7LX2/PEwB4w==
